(setq *properties-from-map* (remove-duplicates '(	|referenceSequence|
 	|address|
 	|name|
 	|templateEvent|
 	|hasEvent|
 	|ISBN|
 	|chapterTitle|
 	|pages|
 	|publisher|
 	|year|
 	|chapterAuthors|
 	|hasCandidate|
 	|activity|
 	|physicalEntity|
 	|activeUnit|
 	|literatureReference|
 	|isChimeric|
 	|totalProt|
 	|maxHomologues|
 	|inferredProt|
 	|hasComponent|
 	|entityOnOtherCell|
 	|hasComponent|
 	|includedLocation|
 	|species|
 	|concurrentEvents|
 	|focusEntity|
 	|definition|
 	|name|
 	|modification|
 	|secondCoordinate|
 	|thing|
 	|property_name|
 	|property_value|
 	|property_value_type|
 	|identifier|
 	|referenceDatabase|
 	|crossReference|
 	|__is_ghost|
 	|_timestamp|
 	|created|
 	|stableIdentifier|
 	|modified|
 	|name|
 	|edgeType|
 	|pathwayDiagram|
 	|pointCoordinates|
 	|sourceVertex|
 	|targetVertex|
 	|physicalEntity|
 	|functionalStatus|
 	|totalProt|
 	|inferredProt|
 	|maxHomologues|
 	|hasMember|
 	|species|
 	|containedInEntityVertex|
 	|endCoordinate|
 	|referenceEntity|
 	|startCoordinate|
 	|hasModifiedResidue|
 	|_doRelease|
 	|definition|
 	|evidenceType|
 	|goBiologicalProcess|
 	|releaseDate|
 	|releaseStatus|
 	|authored|
 	|compartment|
 	|crossReference|
 	|disease|
 	|edited|
 	|figure|
 	|inferredFrom|
 	|literatureReference|
 	|name|
 	|orthologousEvent|
 	|precedingEvent|
 	|reviewed|
 	|revised|
 	|species|
 	|summation|
 	|definition|
 	|instanceOf|
 	|name|
 	|definition|
 	|identifier|
 	|referenceDatabase|
 	|instanceOf|
 	|name|
 	|synonym|
 	|url|
 	|coordinate|
 	|endPositionInReferenceSequence|
 	|startPositionInReferenceSequence|
 	|frontPageItem|
 	|functionalStatusType|
 	|structuralVariant|
 	|definition|
 	|name|
 	|accession|
 	|definition|
 	|referenceDatabase|
 	|componentOf|
 	|hasPart|
 	|instanceOf|
 	|name|
 	|negativelyRegulate|
 	|positivelyRegulate|
 	|regulate|
 	|accession|
 	|definition|
 	|referenceDatabase|
 	|componentOf|
 	|hasPart|
 	|instanceOf|
 	|name|
 	|accession|
 	|definition|
 	|referenceDatabase|
 	|componentOf|
 	|ecNumber|
 	|hasPart|
 	|instanceOf|
 	|name|
 	|negativelyRegulate|
 	|positivelyRegulate|
 	|regulate|
 	|hasInstance|
 	|species|
 	|modification|
 	|_applyToAllEditedInstances|
 	|dateTime|
 	|note|
 	|author|
 	|equivalentTo|
 	|secondReferenceSequence|
 	|journal|
 	|pages|
 	|pubMedIdentifier|
 	|volume|
 	|year|
 	|ontology|
 	|referenceEntity|
 	|parameter|
 	|value|
 	|doi|
 	|isCanonical|
 	|locatedEvent|
 	|maxX|
 	|maxY|
 	|minX|
 	|minY|
 	|height|
 	|storedATXML|
 	|width|
 	|representedPathway|
 	|hasEvent|
 	|eMailAddress|
 	|firstname|
 	|initial|
 	|project|
 	|surname|
 	|url|
 	|affiliation|
 	|figure|
 	|authored|
 	|cellType|
 	|definition|
 	|goCellularComponent|
 	|compartment|
 	|crossReference|
 	|disease|
 	|edited|
 	|figure|
 	|hasDomain|
 	|inferredFrom|
 	|inferredTo|
 	|literatureReference|
 	|name|
 	|reviewed|
 	|revised|
 	|summation|
 	|maxUnitCount|
 	|minUnitCount|
 	|totalProt|
 	|maxHomologues|
 	|inferredProt|
 	|repeatedUnit|
 	|species|
 	|title|
 	|author|
 	|reverseReaction|
 	|totalProt|
 	|maxHomologues|
 	|inferredProt|
 	|locatedEvent|
 	|locationContext|
 	|sourceX|
 	|sourceY|
 	|targetX|
 	|targetY|
 	|pointCoordinates|
 	|isChimeric|
 	|catalystActivity|
 	|entityFunctionalStatus|
 	|entityOnOtherCell|
 	|input|
 	|normalReaction|
 	|output|
 	|requiredInputComponent|
 	|accessUrl|
 	|url|
 	|name|
 	|identifier|
 	|referenceDatabase|
 	|crossReference|
 	|name|
 	|otherIdentifier|
 	|referenceGene|
 	|referenceTranscript|
 	|atomicConnectivity|
 	|formula|
 	|variantIdentifier|
 	|isoformParent|
 	|atomicConnectivity|
 	|formula|
 	|referenceGene|
 	|checksum|
 	|isSequenceChanged|
 	|sequenceLength|
 	|species|
 	|comment|
 	|description|
 	|geneName|
 	|keyword|
 	|secondaryIdentifier|
 	|authored|
 	|regulatedEntity|
 	|regulationType|
 	|regulator|
 	|releaseDate|
 	|instanceOf|
 	|name|
 	|edited|
 	|figure|
 	|literatureReference|
 	|name|
 	|reviewed|
 	|revised|
 	|summation|
 	|coordinate|
 	|psiMod|
 	|endCoordinate|
 	|referenceEntity|
 	|startCoordinate|
 	|species|
 	|referenceEntity|
 	|figure|
 	|identifier|
 	|identifierVersion|
 	|referenceDatabase|
 	|text|
 	|literatureReference|
 	|superTaxon|
 	|crossReference|
 	|name|
 	|coordinate|
 	|psiMod|
 	|uniformResourceLocator|
 	|height|
 	|pathwayDiagram|
 	|representedInstance|
 	|width|
 	|x|
 	|y|
 	|providerCount|
 	|searchableTerm|
 	|species|
 	|vertexCount|
 	|termProvider|
 	|vertex|
 	|changedAttribute|
 	|previousValue|
 	|curatorComment|
 	|reason|
 	|deletedInstanceDB_ID|
 	|replacementInstances|
 	|changedInstanceDB_ID|
 	|instanceEdit|
 	|attributeValuesBeforeChange|
 	|releaseDate|
 	|releaseNumber|
 	|uri|
 	|uri|
 	|uri|
)))
